# Android SDK Auto-Fix Script
# Automatically finds and configures Android SDK for the mobile app
$ErrorActionPreference = "Stop"

Write-Host "`n🔧 Android SDK Auto-Configuration" -ForegroundColor Cyan
Write-Host "=====================================`n" -ForegroundColor Cyan

Write-Host "🔍 Searching for Android SDK..." -ForegroundColor Yellow

# Common SDK locations to check
$possiblePaths = @(
    "$env:USERPROFILE\AppData\Local\Android\Sdk",
    "$env:LOCALAPPDATA\Android\Sdk",
    "C:\Android\Sdk",
    "C:\Program Files\Android\Sdk",
    "C:\Program Files (x86)\Android\Sdk",
    "$env:USERPROFILE\Android\Sdk"
)

$sdkPath = $null
foreach ($path in $possiblePaths) {
    Write-Host "  Checking: $path" -ForegroundColor Gray
    if (Test-Path $path) {
        # Verify it's a valid SDK by checking for platform-tools
        if (Test-Path "$path\platform-tools") {
            $sdkPath = $path
            Write-Host "✅ Found valid Android SDK at: $sdkPath" -ForegroundColor Green
            break
        }
    }
}

if ($null -eq $sdkPath) {
    Write-Host "`n❌ Android SDK not found in common locations`n" -ForegroundColor Red
    Write-Host "Please install Android Studio from: https://developer.android.com/studio" -ForegroundColor Yellow
    Write-Host "Or manually set ANDROID_HOME to your SDK location`n" -ForegroundColor Yellow
    exit 1
}

# Ensure the android directory exists
$androidDir = "mobile-app\android"
if (-not (Test-Path $androidDir)) {
    Write-Host "❌ mobile-app\android directory not found" -ForegroundColor Red
    Write-Host "Are you running this from the project root?" -ForegroundColor Yellow
    exit 1
}

# Create local.properties
Write-Host "`n📝 Creating local.properties..." -ForegroundColor Yellow
$localPropsPath = "$androidDir\local.properties"

# Convert backslashes to forward slashes or escape them
$sdkPathEscaped = $sdkPath -replace '\\', '\\\\'

$localPropsContent = @"
## This file is automatically generated by fix-android-sdk.ps1
## Location of the Android SDK
sdk.dir=$sdkPathEscaped
"@

New-Item -Path $localPropsPath -ItemType File -Force | Out-Null
Set-Content -Path $localPropsPath -Value $localPropsContent -Encoding UTF8

Write-Host "✅ Created: $localPropsPath" -ForegroundColor Green
Write-Host "   Content: sdk.dir=$sdkPathEscaped" -ForegroundColor Gray

# Set environment variable
Write-Host "`n🔧 Setting ANDROID_HOME environment variable..." -ForegroundColor Yellow

try {
    [System.Environment]::SetEnvironmentVariable('ANDROID_HOME', $sdkPath, 'User')
    Write-Host "✅ Set ANDROID_HOME=$sdkPath" -ForegroundColor Green
} catch {
    Write-Host "⚠️  Could not set environment variable (may need admin rights)" -ForegroundColor Yellow
}

# Check if ANDROID_HOME is set in current session
$currentAndroidHome = $env:ANDROID_HOME
if ($currentAndroidHome -ne $sdkPath) {
    Write-Host "⚠️  Setting ANDROID_HOME for current session..." -ForegroundColor Yellow
    $env:ANDROID_HOME = $sdkPath
}

# Verify SDK tools
Write-Host "`n🔎 Verifying Android SDK installation..." -ForegroundColor Yellow

$tools = @{
    "Platform Tools" = "$sdkPath\platform-tools\adb.exe"
    "Build Tools" = "$sdkPath\build-tools"
}

foreach ($tool in $tools.GetEnumerator()) {
    if (Test-Path $tool.Value) {
        Write-Host "  ✅ $($tool.Key): Found" -ForegroundColor Green
    } else {
        Write-Host "  ⚠️  $($tool.Key): Not found" -ForegroundColor Yellow
    }
}

Write-Host "`n✅ Android SDK configured successfully!`n" -ForegroundColor Green
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Restart your terminal/IDE" -ForegroundColor White
Write-Host "  2. cd mobile-app" -ForegroundColor White
Write-Host "  3. npx expo prebuild --clean" -ForegroundColor White
Write-Host "  4. npx expo run:android`n" -ForegroundColor White

Write-Host "⚠️  IMPORTANT: Please restart your terminal/IDE now!`n" -ForegroundColor Yellow
