import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Platform } from 'react-native';

export class PDFService {
    static async generateQuizPDF(title: string, quizData: any[]): Promise<void> {
        const questionsHtml = quizData.map((q, i) => `
            <div class="question-box">
                <p class="question"><strong>${i + 1}. ${q.question}</strong></p>
                <ul class="options">
                    ${q.options.map((opt: string, oi: number) => `
                        <li>[ ] ${opt}</li>
                    `).join('')}
                </ul>
            </div>
        `).join('');

        const html = `
            <html>
                <head>
                    <style>
                        body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #333; }
                        h1 { color: #2563EB; border-bottom: 2px solid #2563EB; padding-bottom: 10px; }
                        .question-box { margin-bottom: 30px; page-break-inside: avoid; }
                        .question { font-size: 18px; }
                        .options { list-style: none; padding-left: 20px; }
                        li { margin-bottom: 10px; font-size: 16px; }
                        .footer { margin-top: 50px; font-size: 12px; color: #666; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }
                    </style>
                </head>
                <body>
                    <h1>Quiz: ${title}</h1>
                    ${questionsHtml}
                    <div class="footer">
                        Generated by Study Buddy AI.
                    </div>
                </body>
            </html>
        `;

        try {
            if (Platform.OS === 'web') {
                await Print.printAsync({ html });
            } else {
                const { uri } = await Print.printToFileAsync({ html });
                await Sharing.shareAsync(uri);
            }
        } catch (error) {
            console.error('[PDFService] Error:', error);
        }
    }

    static async generateSummaryPDF(title: string, content: string): Promise<void> {
        const html = `
            <html>
                <head>
                    <style>
                        body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #333; line-height: 1.6; }
                        h1 { color: #2563EB; border-bottom: 2px solid #2563EB; padding-bottom: 10px; }
                        .content { font-size: 16px; white-space: pre-wrap; }
                        .footer { margin-top: 50px; font-size: 12px; color: #666; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }
                    </style>
                </head>
                <body>
                    <h1>Summary: ${title}</h1>
                    <div class="content">${content}</div>
                    <div class="footer">
                        Generated by Study Buddy AI.
                    </div>
                </body>
            </html>
        `;

        try {
            if (Platform.OS === 'web') {
                await Print.printAsync({ html });
            } else {
                const { uri } = await Print.printToFileAsync({ html });
                await Sharing.shareAsync(uri);
            }
        } catch (error) {
            console.error('[PDFService] Error:', error);
        }
    }
}
